FROM nimmis/apache-php7

COPY src/index.php /var/www/html/index.php
COPY src/js /var/www/html/js
COPY src/css /var/www/html/css
COPY dist/iZwz9i9xnerwj6o7h40eauZ.png /var/www/html/iZwz9i9xnerwj6o7h40eauZ.png

RUN rm -rf /var/www/html/index.html


